---

- name: Perform steps configuring tuned
  block:
    - name: Enable and start tuned
      service:
        name: tuned
        state: started
        enabled: yes

    - name: Show currently active tuned profile
      shell: /usr/sbin/tuned-adm active | grep ":" | cut -d ":" -f 2 | awk '{$1=$1;print}'
      check_mode: no
      register: __sap_hana_preconfigure_register_current_tuned_profile
      changed_when: false

    - name: Display the output of the tuned-adm active command
      debug:
        var: __sap_hana_preconfigure_register_current_tuned_profile.stdout_lines, __sap_hana_preconfigure_register_current_tuned_profile.stderr_lines

    - name: Switch to tuned profile sap-hana if not currently active
      block:
        - name: Switch to tuned profile sap-hana
          command: /usr/sbin/tuned-adm profile sap-hana

        - name: Show new active tuned profile
          shell: /usr/sbin/tuned-adm active | grep ":" | cut -d ":" -f 2 | awk '{$1=$1;print}'
          check_mode: no
          register: __sap_hana_preconfigure_register_new_tuned_profile
          changed_when: false

        - name: Display the output of the tuned-adm active command after switching to profile sap-hana
          debug:
            var: __sap_hana_preconfigure_register_new_tuned_profile.stdout_lines, __sap_hana_preconfigure_register_new_tuned_profile.stderr_lines

      when:
        - __sap_hana_preconfigure_register_current_tuned_profile.stdout != 'sap-hana'

  when:
    - sap_hana_preconfigure_use_tuned
    - (ansible_architecture != "ppc64le" or (ansible_architecture == "ppc64le" and ansible_distribution_version != "8.0"))

- name: Perform additional steps for RHEL 8.0 ppc64le
  block:
    - name: RHEL 8.0 ppc64le - create directory /etc/tuned/sap-hana-ppc64le
      file:
        path: /etc/tuned/sap-hana-ppc64le
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: RHEL 8.0 ppc64le - copy file /etc/tuned/sap-hana-ppc64le/tuned.conf
      copy:
        src: etc/tuned/sap-hana-ppc64le/tuned.conf
        dest: /etc/tuned/sap-hana-ppc64le/tuned.conf
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: RHEL 8.0 ppc64le - show currently active tuned profile
      shell: set -o pipefail && /usr/sbin/tuned-adm active | grep ":" | cut -d ":" -f 2 | awk '{$1=$1;print}'
      check_mode: no
      register: __sap_hana_preconfigure_register_current_tuned_profile_ppc64le
      changed_when: false

    - name: RHEL 8.0 ppc64le - Display the output of the tuned-adm active command
      debug:
        var: __sap_hana_preconfigure_register_current_tuned_profile_ppc64le.stdout_lines,
             __sap_hana_preconfigure_register_current_tuned_profile_ppc64le.stderr_lines

    - name: RHEL 8.0 ppc64le - switch to tuned profiles sap-hana sap-hana-ppc64le if not currently active
      block:
        - name: Switch to tuned profiles sap-hana sap-hana-ppc64le
          command: /usr/sbin/tuned-adm profile sap-hana sap-hana-ppc64le

        - name: RHEL 8.0 ppc64le - Show new active tuned profile
          shell: set -o pipefail && /usr/sbin/tuned-adm active | grep ":" | cut -d ":" -f 2 | awk '{$1=$1;print}'
          register: __sap_hana_preconfigure_register_new_tuned_profile_ppc64le
          changed_when: false

        - name: RHEL 8.0 ppc64le - Display the output of the tuned-adm active command
          debug:
            var: __sap_hana_preconfigure_register_new_tuned_profile_ppc64le.stdout_lines,
                 __sap_hana_preconfigure_register_new_tuned_profile_ppc64le.stderr_lines

      when:
        - __sap_hana_preconfigure_register_current_tuned_profile_ppc64le.stdout != 'sap-hana sap-hana-ppc64le'

  when:
    - sap_hana_preconfigure_use_tuned
    - ansible_architecture == "ppc64le"
    - ansible_distribution_version == "8.0"
