---

- name: Assert 2777782-1
  debug:
    msg: "SAP note 2777782 Step 1: Configure SELinux"

- name: Notify about where SELinux is asserted
  debug:
    msg: "SELinux is already asserted by role sap-preconfigure."
