---

- name: Configure 2777782-10
  debug:
    msg: "SAP note 2777782 Step 10: Increase pidmax"

- name: Notify about where pidmax is set
  debug:
    msg: "Kernel parameter pidmax is already set by role sap-preconfigure."
